Train GCNN model

  $ cp -R ${TESTDIR}/* .

# Test mse_loss model

  $ train_gcnn.py \
  > --data_path files/data.lz4 \
  > --record_path ${CRAMTMP}/temp.csv \
  > --model_path ${CRAMTMP}/temp.h5 \
  > --metrics_path ${CRAMTMP}/temp.dat \
  > --epochs 2 \
  > --batch_size 2 \
  > --learning_rate 0.1 \
  > --channels 2 2 \
  > --n_layers 2 \
  > --seed 0 \
  > "mse_loss"
  Traceback (most recent call last):
    File "/Users/alejandro.gilley/Projects/miniconda/envs/chemgraph/bin/train_gcnn.py", line 7, in <module>
      exec(compile(f.read(), __file__, 'exec'))
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 193, in <module>
      main(arguments)
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 34, in main
      dataset.apply(LayerPreprocess(ECCConv))
  AttributeError: 'GraphDB' object has no attribute 'apply'
  [1]
  $ diff files/mse_train.csv ${CRAMTMP}/temp.csv
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.csv: No such file or directory
  [2]
  $ diff files/mse_metrics.dat ${CRAMTMP}/temp.dat
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.dat: No such file or directory
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/mse_model.h5 /model_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/mse_model.h5 /optimizer_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]

# Test maxlike_mse_loss model

  $ train_gcnn.py \
  > --data_path files/data.lz4 \
  > --record_path ${CRAMTMP}/temp.csv \
  > --model_path ${CRAMTMP}/temp.h5 \
  > --metrics_path ${CRAMTMP}/temp.dat \
  > --epochs 2 \
  > --batch_size 2 \
  > --learning_rate 0.1 \
  > --channels 2 2 \
  > --n_layers 2 \
  > --seed 0 \
  > "maxlike_mse_loss" 
  Traceback (most recent call last):
    File "/Users/alejandro.gilley/Projects/miniconda/envs/chemgraph/bin/train_gcnn.py", line 7, in <module>
      exec(compile(f.read(), __file__, 'exec'))
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 193, in <module>
      main(arguments)
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 34, in main
      dataset.apply(LayerPreprocess(ECCConv))
  AttributeError: 'GraphDB' object has no attribute 'apply'
  [1]
  $ diff files/max_train.csv ${CRAMTMP}/temp.csv
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.csv: No such file or directory
  [2]
  $ diff files/max_metrics.dat ${CRAMTMP}/temp.dat
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.dat: No such file or directory
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/max_model.h5 /model_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/max_model.h5 /optimizer_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]

# Test maxlike_cse_loss model

  $ train_gcnn.py \
  > --data_path files/data.lz4 \
  > --record_path ${CRAMTMP}/temp.csv \
  > --model_path ${CRAMTMP}/temp.h5 \
  > --metrics_path ${CRAMTMP}/temp.dat \
  > --epochs 2 \
  > --batch_size 2 \
  > --learning_rate 0.1 \
  > --channels 2 2 \
  > --n_layers 2 \
  > --seed 0 \
  > "maxlike_cse_loss"
  Traceback (most recent call last):
    File "/Users/alejandro.gilley/Projects/miniconda/envs/chemgraph/bin/train_gcnn.py", line 7, in <module>
      exec(compile(f.read(), __file__, 'exec'))
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 193, in <module>
      main(arguments)
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 34, in main
      dataset.apply(LayerPreprocess(ECCConv))
  AttributeError: 'GraphDB' object has no attribute 'apply'
  [1]
  $ diff files/cse_train.csv ${CRAMTMP}/temp.csv
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.csv: No such file or directory
  [2]
  $ diff files/cse_metrics.dat ${CRAMTMP}/temp.dat
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.dat: No such file or directory
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/cse_model.h5 /model_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/cse_model.h5 /optimizer_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]

# Test maxlike_tobit_loss model

  $ train_gcnn.py \
  > --data_path files/data.lz4 \
  > --record_path ${CRAMTMP}/temp.csv \
  > --model_path ${CRAMTMP}/temp.h5 \
  > --metrics_path ${CRAMTMP}/temp.dat \
  > --epochs 2 \
  > --batch_size 2 \
  > --learning_rate 0.1 \
  > --channels 2 2 \
  > --n_layers 2 \
  > --seed 0 \
  > "maxlike_tobit_loss"
  Traceback (most recent call last):
    File "/Users/alejandro.gilley/Projects/miniconda/envs/chemgraph/bin/train_gcnn.py", line 7, in <module>
      exec(compile(f.read(), __file__, 'exec'))
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 193, in <module>
      main(arguments)
    File "/Users/alejandro.gilley/Projects/ChemGraphs/ChemGraphs/gcnn/apps/train_gcnn.py", line 34, in main
      dataset.apply(LayerPreprocess(ECCConv))
  AttributeError: 'GraphDB' object has no attribute 'apply'
  [1]
  $ diff files/tobit_train.csv ${CRAMTMP}/temp.csv
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.csv: No such file or directory
  [2]
  $ diff files/tobit_metrics.dat ${CRAMTMP}/temp.dat
  diff: /var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.dat: No such file or directory
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/tobit_model.h5 /model_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]
  $ h5diff -d 1e-1 ${CRAMTMP}/temp.h5 files/tobit_model.h5 /optimizer_weights
  h5diff: </var/folders/xd/btlk4xt16hngrj6zv8xnllfh0000gn/T/cramtests-cg5fesea/temp.h5>: unable to open file
  [2]
